name: Nix
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  schedule:
    # Run once per day
    - cron: '0 0 * * *'

env:
  CI_REGISTRY: ghcr.io

jobs:
  build:
    strategy:
      # Keep building the other channels if one fails
      fail-fast: false
      matrix:
        channel:
          - nixos-unstable
          - nixos-22.05
          - nixos-22.11

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.CI_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/install-nix-action@v20
      - run: nix-shell --run ./ci.sh
        env:
          NIXPKGS_CHANNEL: '${{ matrix.channel }}'
